$hypr = ~/.config/hypr
# source = $hypr/colors.conf # for custom color

# GENERAL
general {
  no_fade_in = false
  grace = 1
  disable_loading_bar = false
  hide_cursor = true
  ignore_empty_input = true
  text_trim = true
}

background {
    monitor = 
    path = screenshot
    blur_passes = 1
    vibrancy_darkness = 0
}

# TIME
label {
    monitor = 
    text = cmd[update:1000] date +"%I:%M"
    color = rgb(232, 234, 237)
    shadow_color = rgb(0,0,0)
    font_size = 80
    font_family = JetBrainsMono Nerd Font ExtraBold
    position = 0, 170
    halign = center
    valign = center
}

# AM/PM
label {
    monitor =
    text = cmd[update:1000] date +"%p"
    color = rgb(232, 234, 237)
    font_family = JetBrainsMono Nerd Font Bold
    font_size = 20
    position = 180, 145
    halign = center
    valign = center
}

# DATE
label {
    monitor = 
    text = cmd[update:1000] date +"%b,  %d %A"
    color = rgb(232, 234, 237)
    font_size = 12
    font_family = JetBrainsMono Nerd Font Bold
    position = 0, 100
    halign = center
    valign = center
}

# PFP
image {
    monitor =
    path = /home/dragon/Downloads/cat.jpeg
    size = 90
    border_size = 2
    border_color = rgb(232, 234, 237)
    rounding = 100
    position = 0, 20
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    outer_color = rgba(4a5157ff)

    font_color = rgb(232, 234, 237)
    fade_on_empty = false
    rounding = 15

    position = 0, -70
    halign = center
    valign = center
}
# Information
label {
    monitor = 
    text =  $USER
    font_family = JetBrainsMono Nerd Font Propo ExtraBold
    valign = bottom
    font_size = 11
    position = 0, 20
    halign = center
    color = rgb(232, 234, 237)
}
